//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webapp.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int ID_Venta { get; set; }
        public Nullable<int> ID_Zapatilla { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
